# Generated by Django 4.2.7 on 2026-03-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0002_electioncontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='electioncontrol',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
